package com.virtualap.app.util

object Constants {
    const val VAP_DIR = "/data/local/virtualap"
    const val PREFS_NAME = "virtualap_prefs"
    const val KEY_ROOT_AVAILABLE = "root_available"
    const val KEY_FOLLOW_SYSTEM_THEME = "follow_system_theme"
    const val KEY_DARK_THEME = "dark_theme"
    const val KEY_AMOLED_MODE = "amoled_mode"
    const val KEY_USE_DYNAMIC_COLOR = "use_dynamic_color"
    const val KEY_THEME_PALETTE = "theme_palette"
    const val KEY_AP_SSID = "ap_ssid"
    const val KEY_AP_PASSWORD = "ap_password"
    const val KEY_AP_BAND = "ap_band"
    const val KEY_AP_CHANNEL = "ap_channel"
    const val KEY_AP_WIDTH = "ap_width"
    const val KEY_AP_UPSTREAM = "ap_upstream"
    const val KEY_AP_GATEWAY = "ap_gateway"
    const val KEY_AP_DNS = "ap_dns"
    const val KEY_AP_HIDDEN = "ap_hidden"
    const val KEY_AP_SECURITY = "ap_security"
    const val KEY_AP_PMF = "ap_pmf"
    const val KEY_AP_TTL_FIX = "ap_ttl_fix"
    const val KEY_AP_AUTO_SHUTDOWN = "ap_auto_shutdown"
    const val KEY_AP_MAX_CLIENTS = "ap_max_clients"
    const val KEY_AP_CONTAINER_MODE = "ap_container_mode"
    const val KEY_AP_CONTAINER = "ap_container"
    const val KEY_HAS_SEEN_ROOT_CHECK = "has_seen_root_check"
    const val KEY_PAYLOAD_VERSION = "payload_version"
}
